### PR TITLE
Docstrings on lone identifiers and SQLStrings language injection

### PR DESCRIPTION
**Pull request by steffenhaug**
# Docstrings on identifiers
I modified the queries for docstring highlights, as well as Markdown language injection into docstrings, to support docstrings followed by an identifier:

```Julia
"..."
f
```

While this is not the preferred style, [it is documented](https://docs.julialang.org/en/v1/manual/documentation/#Functions-and-Methods-2), so unless highlighting docstrings in this sequence of nodes breaks something else that I haven't thought of, I reckon it makes sense to do so.

# SQL language injection
Additionally, I added SQL language injection for command literals prefixed with `sql`, to work with [SQLStrings.jl](https://github.com/JuliaComputing/SQLStrings.jl). This might be beyond the scope for a package providing basic Julia language features, so feel free to reject that. Maybe it should be a separate plugin?

It is implemented in the same way the regex language injection is, so unfortunately the entire string node, including quotes and the `sql` prefix is re-parsed as SQL. I suspect there might be edge cases where this breaks, but so far all the queries I have in my codebase seems to parse in a sensible way. I wish there was a way to apply language injection to only the range with actual string content, but from what I can tell this is not possible without modifying the Julia Tree-sitter grammar.

### CODE REVIEW

**Comment by piechologist** [comment]
Thanks for the PR! I'd like to have this kind of docstrings too but unfortunately, there's a side effect:
```julia
func("that makes me a docstring", foo)
@info "that makes me a docstring" foo
```
That's why I ended up with just an `open_tuple` of identifiers because this query is specific enough.

I don't see a problem with the SQL commit though. Let me think about possible edge case…

**Comment by steffenhaug** [comment]
Oh, that's unfortuante. Good catch!

Maybe it is possible to query for string nodes before identifier nodes, which are not children of function call nodes or macro invocation nodes? I'll have a look around the documentation and see if I can work something out.

**Comment by steffenhaug** [comment]
I made some changes to the queries. Now I only inject markdown into string literals immediately followed by identifiers if they are children of `source_file`-nodes or `module_definition`-nodes.

I also added a query that injects markdown into string literals if they are the first child of a `@doc` macro.

This now highlights like this:



I added a test file with syntax highlighting test cases to the repository if you want it. Maybe the root folder isn't the best place for it, but it might help other newcomers not miss edge cases like I did :-p Just let me know, and I'll remove it or move it to somewhere more sensible.

**Review by piechologist — CHANGES_REQUESTED** [review]
Excellent!

Let's move the old `(open_tuple (identifier))` into your new blocks. That way, we keep similar things together plus, your queries are more specific 👍. For instance:
```scheme
(source_file
  (string_literal) @comment.doc
  .
  [
    (identifier)
    (open_tuple (identifier))
  ])
```
Please check the indentation (2 spaces).

I think we should put the test cases into `syntax-test-cases/docs.jl` so we can later add more. There's also the repo [julia-syntax-test-cases](https://github.com/JuliaEditorSupport/julia-syntax-test-cases) but that hasn't been touched in 5 years.

**Comment by steffenhaug** [comment]
Alright I have moved the open tuple case and made a directory for syntax test cases.

I also had the realization between yesterday and now that there are actually a lot of nodes which are technically valid parent nodes of docstrings. What i would ideally want to do is obviously something along the lines of 

```
(![
  call_expression macro_call
] ...)
```

But filtering based on the parent node like this does not seem possible from what i have gathered, so I think we are left having to list out as many cases as we thing is reasonable to handle.

I went ahead and added `begin`- and `let`-blocks as well. Let me know if you can think of others that are worth covering.

**Comment by piechologist** [comment]
> I also had the realization between yesterday and now […]

Yep, Tree-sitter queries appear in our dreams. Writing parsers is supposed to be [zen-like](https://tree-sitter.github.io/tree-sitter/creating-parsers). Well, we're just dealing with profane queries here.

> […] there are actually a lot of nodes which are technically valid parent nodes of docstrings. What i would ideally want to do is obviously something along the lines of `(![ call_expression macro_call ] ...)`

In my experience, it's better to be as specific as possible or you may get bitten in some other places. I would be careful with `![…]`.

Do you have a special use case for the `let_statement` and `compound_statement` queries? I grepped base Julia and all my installed packages for `^\s+"""` (code inside let blocks should be indented) but I didn't see any docstring that would require those two queries. I'd rather merge without those… 

Also, I think we shouldn't deviate too much from [nvim](https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/julia). I borrowed most of their queries and I'd like to keep zed-julia close to their repo.

**Comment by steffenhaug** [comment]
> Do you have a special use case for the `let_statement` and `compound_statement` queries? I grepped base Julia and all my installed packages for `^\s+"""` (code inside let blocks should be indented) but I didn't see any docstring that would require those two queries. I'd rather merge without those…

I think you could see docstrings in compound statements if people wanted to group definitions in a Pluto cell for example, and then opened the script in Zed, but supporting that is borderline ridiculous. I went and checked the documentation, and a bit down in the [advanced usage](https://docs.julialang.org/en/v1/manual/documentation/#Advanced-Usage) section, they even specifically state:

> Documentation in non-toplevel blocks, such as `begin`, `if`, `for`, and `let`, should be added to the documentation system via `@doc`

So you are right; there is no reason to support it. I will remove it.

**Review by piechologist — APPROVED** [review]
I've tested the changes locally on my machine. All looks good.

Adding the sql injection is fine because it does no harm even when [SQLStrings.jl](https://github.com/JuliaComputing/SQLStrings.jl) is not installed. That package sees 3k monthly downloads according to JuliaHub and I guess the highlighting will benefit many users.

Thank you for your PR!

**Pull request merged**
