### PR TITLE
Docstrings on annotated definitions + on strings stolen by preceding top level macros

### PR DESCRIPTION
**Pull request by steffenhaug**
NOTE: This is absolutely horrendous! It is at least a solution to https://github.com/JuliaEditorSupport/zed-julia/issues/15#issue-2502596294 as promised, but I'm more than happy to leave this out for now and implement it in a cleaner way if/when we can get the grammar fixed.

The following cases were broken before, but are now highlighted correctly:

Essentially, the problem is that the docstrings are incorrectly parsed as arguments to the preceding macro. The workaround is querying for items which can have docstrings and are immediately following a macro call which has a string as its last argument, but not as its only argument. This very specific query avoids incorrectly highlighting strings in common macros like this:

### CODE REVIEW

**Review by piechologist — COMMENTED** [review]
Looks less horrendous than I'd expected 😃!
- Added `macro_definition` twice to align with the upstream draft.
- Gonna test it tomorrow. Thank you as always 👍!

**Comment by steffenhaug** [comment]
> Looks less horrendous than I'd expected 😃!

Heh :-) Yeah, its not really a complicated query, I might have exaggerated a little. It is just silly that this needs to be done like this in the first place. As far as ugly workarounds go, I suppose you can argue this is quite mild.

I went ahead and added some syntax test cases with some clarifying comments, in particular the cases where this workaround leads to incorrect highlighting. I think this should give a pretty good overview of the benefits and drawbacks of the workaround:



I could still go either way as to whether this is sensible to merge. I don't know off the top of my head any macros with more than one argument that use string literals as their last argument, which are also common to use at the top of a file, but they may very well exist.

**Comment by piechologist** [comment]
I like your solution. It's definitely better than what we had before and it covers the common patterns. Docstrings are important and it's wrong to treat them as plain strings. We need these queries in injections.scm anyway so why not use them for highlighting as well. BTW, that was my thinking when I wrote this awful block to match short function definitions. I  had to do it for outline.scm (have you ever tried the outline modal?) and carried it over to highlights.scm.
 
1. The two test cases for `begin` and `let` blocks can be either removed or changed to "should not have MD injected." We ought to use `@doc` per the Julia manual. The queries are correct.

2. An idea for the two broken test cases at the end of docstrings.jl (from line 107 on): docstrings are usually triple-quoted and arguments are more often than not single-quoted. We improve our chances of being right with:
```scm
(source_file
  (string_literal) @comment.doc
  .
  [
    (identifier)
    (macrocall_expression)
    (open_tuple
      (identifier))
  ]
  (#match? @comment.doc "^\"\"\""))   ; ADDED 
```
Not pretty I know… would need to be done in all of your four blocks (2 × module_definition and 2 × source_file) plus the same in injections.scm. What do you think?

**Comment by steffenhaug** [comment]
> have you ever tried the outline modal?

Didn't even know about it until now :v)


> The two test cases for `begin` and `let` blocks can be either removed or changed to "should not have MD injected." We ought to use `@doc` per the Julia manual. The queries are correct.

Oh crap, I thought I already did before I finished the last PR. Somehow they made their way into Main, so I got them back when i merged the upstream changes. I will remove them.


> An idea for the two broken test cases at the end of docstrings.jl (from line 107 on): docstrings are usually triple-quoted and arguments are more often than not single-quoted. We improve our chances of being right with: ...

That's clever! Pretty sure that should cover virtually all reasonable cases. As you say, it is not pretty, but it's not that gnarly so I reckon it's worth it.

**Comment by steffenhaug** [comment]
> Not pretty I know… would need to be done in all of your four blocks (2 × module_definition and 2 × source_file) plus the same in injections.scm. What do you think?

It should only be necessary in the queries for docstrings stolen by macros, so I added the match to the ones with `macrocall_expression`s only, that avoids breaking stuff like this:

```Julia
"single-line docstring"
function foo end
```

Which i think is actually sometimes found in the wild.

However in testing this, I noticed that this doesn't currently work anyways, because the basic Markdown injection query is restricted to triple-quoted strings.

**Comment by steffenhaug** [comment]
Removing the restriction of the basic markdown injection query to single-quoted strings doesn't seem to have led to any regressions in the test cases as far as I can tell. I thought that might lead to function calls and macro calls being broken again, but it looks like it's fine. Probably precedence I guess.

**Comment by piechologist** [comment]
You made some good points! Let's think this over again. We know it's messy and impossible to do right because of the ambiguous syntax tree.

Looking at some real code from a user's view gives the impression that the highlighting is a bit unpredictable. We have so many exceptions now.

How about incorporating the Julia manual as closely as possible? 
1. We dump the original query (note: I realized it's missing `(global_statement)`). 
2. We only capture top level docstrings (the way you did in your first commit). Nested docstrings are supposed to use the `@doc` macro anyway.
3. We accept single- and triple-quoted docstrings. I assume restricting to triple-quoted strings in injections.scm was done to make nvim's `offset` predicate work.
4. Expressions may be prefixed with one ore more macro calls. That's very common.
5. We would only need three queries in highlights.scm (I mixed together what we had):
```scm
((macrocall_expression
  (macro_identifier "@" (identifier)) @function.macro
  (macro_argument_list
    .
    (string_literal) @comment.doc))
  (#eq? @function.macro "@doc"))

(source_file
  [
    (string_literal) @comment.doc
    (macrocall_expression
      (macro_argument_list
      (_)+
      (string_literal) @comment.doc .))
  ]
  .
  [
    (assignment)
    (const_statement)
    (global_statement)
    (abstract_definition)
    (function_definition)
    (macro_definition)
    (module_definition)
    (struct_definition)
    (macrocall_expression)
    (identifier)
    (open_tuple
      (identifier))
  ])

(module_definition
  [
    (string_literal) @comment.doc
    (macrocall_expression
      (macro_argument_list
      (_)+
      (string_literal) @comment.doc .))
  ]
  .
  [
    (assignment)
    (const_statement)
    (global_statement)
    (abstract_definition)
    (function_definition)
    (macro_definition)
    (module_definition)
    (struct_definition)
    (macrocall_expression)
    (identifier)
    (open_tuple
      (identifier))
  ])
```
6. Plus three queries in injections.scm:
```scm
((macrocall_expression
  (macro_identifier "@" (identifier)) @_macro
  (macro_argument_list
    .
    (string_literal) @content))
  (#eq? @_macro "@doc")
  (#set! "language" "markdown"))

(source_file
  [
    (string_literal) @content
    (macrocall_expression
      (macro_argument_list
      (_)+
      (string_literal) @content .))
  ]
  .
  [
    (assignment)
    (const_statement)
    (global_statement)
    (abstract_definition)
    (function_definition)
    (macro_definition)
    (module_definition)
    (struct_definition)
    (macrocall_expression)
    (identifier)
    (open_tuple
      (identifier))
  ]
  (#set! "language" "markdown"))

(module_definition
  [
    (string_literal) @content
    (macrocall_expression
      (macro_argument_list
      (_)+
      (string_literal) @content .))
  ]
  .
  [
    (assignment)
    (const_statement)
    (global_statement)
    (abstract_definition)
    (function_definition)
    (macro_definition)
    (module_definition)
    (struct_definition)
    (macrocall_expression)
    (identifier)
    (open_tuple
      (identifier))
  ]
  (#set! "language" "markdown"))
```
7. Yes, those two test cases in docstrings.jl are still broken but they should be quite rare _at the top level_. One can easily write `@info("Yo", "This should _not_ have markdown injected!")` to clean that up.

**Comment by steffenhaug** [comment]
Those are good suggestions, that cleans it up a lot. I'll probably have time to update the PR sometime this week. From a quick glance it looks like your queries there should pretty much just work.

**Comment by steffenhaug** [comment]
Alright, I pretty much got it done, but I noticed that this approach gives us slightly worse granularity. I thought I might be able to apply the `#match? @content "^\"\"\""` only to the "stolen by preceding macro" case, like this:

```
[
  (string_literal) @content
  ; Workaroud: Find strings stolen as the last argument to a preceding macro
  ; https://github.com/tree-sitter/tree-sitter-julia/issues/150
  ((macrocall_expression
    (macro_argument_list
    (_)+
    (string_literal) @content .))
    (#match? @content "^\"\"\""))
]
```

But that doesn't seem to actually work. All constraints on the capture appear to be global. So restricting `@content` to be triple-quoted will break otherwise sensible docstrings, such as


```Julia
"This _should_ have `markdown` injected!"
function foobar end
```

While most docstrings are triple-quoted, I think single-quoted docstrings are fairly common in the wild for docstrings that are just a one-sentence summary.

I would say we go ahead with it still, and say that for the time being people just have to triple quote docstrings or use `@doc`, because it is a very good restriction for weeding out false positives.

**Review by piechologist — COMMENTED** [review]
Very good! Looks great in my testing! I made a small change because that's the way it's handled in other injections.scm I have seen.

Any other thoughts? Otherwise, I'd merge this…

**Comment by steffenhaug** [comment]
Yeah, that's better. Looks good to me.

**Pull request merged**
